### ISSUE TITLE
Version 0.8.1 should have been released as a breaking change

### ISSUE THREAD

**Issue by Anders429** [robertknight/ocrs#115]
I had previously started using `ocrs` at version `0.8.0`, which has a public dependency on `rten` version `0.10.0`. However, it seems that the newly released `0.8.1` bumped the dependency on `rten` to `0.13.1`, which means that my usages of my own `rten` types in the public API of `ocrs` became broken when running `cargo update`.

As far as I understand, the general consensus is that updating public dependencies, like `rten` in this case, should be considered a breaking change for exactly this reason. Would you consider releasing that change as `0.9.0` instead?

**Comment by robertknight** [comment]
I think you're right. Part of the problem is that this crate specifies the minimum version of rten as v0.13.1 but it actually compiles with older versions down to v0.11.0. This project is an important test case for rten so it needs to use the latest version in development (in Cargo.lock), but the _minimum_ version specified in the crates dependencies shouldn't change as often.

Which breaking changes in rten did you run into?

**Comment by Anders429** [comment]
I didn't specifically hit any breaking changes in `rten`. Instead, I hit issues with incompatible types between versions. Since I was using `rten` version `0.10.0` to interact with `ocrs` version `0.8.0`, the switch to `rten` version `0.13.0` meant I suddenly had a ton of `E0308` compiler errors like this:

```
error[E0308]: mismatched types
    |
138 |                 detection_model: Some(
    |                                  ---- arguments to this enum variant are incorrect
139 |                     Model::load(include_bytes!("../models/text-detection.rten").to_vec()).unwrap(),
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `rten::model::Model`, found `rten::Model`
    |
    = note: `rten::Model` and `rten::model::Model` have similar names, but are actually distinct types
note: `rten::Model` is defined in crate `rten`
   --> ..\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rten-0.10.0\src\model.rs:94:1
    |
94  | pub struct Model {
    | ^^^^^^^^^^^^^^^^
note: `rten::model::Model` is defined in crate `rten`
   --> ..\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rten-0.13.1\src\model.rs:102:1
    |
102 | pub struct Model {
    | ^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `rten` are being used?
```

The quick solution was to pin `ocrs` to version `0.8.0` (I hit this while working on something completely unrelated to my usage of this crate). However, upgrading `rten` to `0.13.0` on my side doesn't actually hit any breaking changes, which matches what you said.
 
However, the community still generally considers bumping a public dependency like this to be a breaking change (see [relevant discussion](https://users.rust-lang.org/t/semver-behavior-for-dependency-changes/73665)). I don't know enough about `rten` to give any kind of example, but I imagine there could be breaking changes someone could theoretically hit in those three breaking releases between `0.10` and `0.13` if they're also using `rten` elsewhere in their project.

**Comment by Anders429** [comment]
And I should add that I don't think there's really a way to use this as a library without including `rten` as a dependency, since you have to provide an `rten::Model` when building [`OcrEngineParams`](https://docs.rs/ocrs/0.8.1/ocrs/struct.OcrEngineParams.html). So in this case the two versions will always come in contact with each other if the one in `ocrs` is upgraded.

**Comment by robertknight** [comment]
Ocrs v0.9.0 has now been published. I decided not to yank v0.8.1 in the end. I'm treating this issue mostly as something to remember for future releases.
